language: generic

services:
    - docker
env:
    - AUTHOR_TESTING=1

install:
    - docker build -t mziescha/perl6-namedqueries .
    - docker run -d -e 'AUTHOR_TESTING=1' -v "$(pwd)":/srv --name p6-namedqueries-test mziescha/perl6-namedqueries /bin/sleep infinity
    - docker exec -it p6-namedqueries-test zef --deps-only install .
    
script:
    - docker exec -it p6-namedqueries-test prove6 -l t
    
after_success:
    - docker stop p6-namedqueries-test
    - docker rm p6-namedqueries-test
    #- if [ "$TRAVIS_BRANCH" == "master" ]; then
    #      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    #      docker push mziescha/perl6-namedqueries;
    #  fi

#notifications:
#    slack: perl6-bailador:FuFG55nk94k5BSOeGMNO5nDh
